config/routes.rb
Rails.application.routes.draw do

  root "misc#homepage"

  get("/", {:controller => "misc", :action => "homepage" })
  get("/athletes/new", { :controller => "athletes", :action => "new" })
  get("/signed_out", { :controller => "misc", :action => "signed_out", :as => "signed_out" })
  get("/admin_dashboard", { :controller => "misc", :action => "admin_dashboard" })


  devise_for :installs
  # Routes for the Athlete resource:

  # CREATE
  post("/insert_athlete", { :controller => "athletes", :action => "create" })
          
  # READ
  get("/athletes", { :controller => "athletes", :action => "index" })
  
  get("/athletes/:path_id", { :controller => "athletes", :action => "show" })
  
  # UPDATE
  get("/edit_athlete/:path_id", { :controller => "athletes", :action => "edit" })

  post("/modify_athlete/:path_id", { :controller => "athletes", :action => "update" })
  
  # DELETE
  get("/delete_athlete/:path_id", { :controller => "athletes", :action => "destroy" })

  #------------------------------

  # Routes for the Brand resource:
  get("/brands/new", { :controller => "brands", :action => "new" })

  # CREATE
  post("/insert_brand", { :controller => "brands", :action => "create" })
          
  # READ
  get("/brands", { :controller => "brands", :action => "index" })
  
  get("/brands/:path_id", { :controller => "brands", :action => "show" })
  
  # UPDATE

  get("/edit_brand/:path_id", { :controller => "brands", :action => "edit" })
  
  post("/modify_brand/:path_id", { :controller => "brands", :action => "update" })
  
  # DELETE
  get("/delete_brand/:path_id", { :controller => "brands", :action => "destroy" })

  #------------------------------

   devise_for :users, { :controllers => { :registrations => "users/registrations" } }

  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"
  
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Indor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-C6CBru/4LrjMNMn3kMbmn6F9AZeOa020r1DE4ChAfBB6I1NGBupBLRPL6kTuyQ0U"
      crossorigin="anonymous"
    >
    <link rel="stylesheet" href="/stylesheets/custom.css">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="<%= root_path %>">Indor</a>

        <ul class="nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= root_path %>">Home</a>
            </li>

            <% if current_user.admin? %>
              <li class="nav-item">
                <a class="nav-link" href="<%= admin_dashboard_path %>">
                  Admin Dashboard
                </a>
              </li>
            <% end %>

            <% if current_user.athlete? %>
              <% me = Athlete.where({ :user_id => current_user.id }).at(0) %>
              <% if me %>
                <li class="nav-item">
                  <a class="nav-link" href="/athletes/<%= me.id %>">
                    My Athlete Profile
                  </a>
                </li>
              <% end %>
            <% elsif current_user.brand? %>
              <% me = Brand.where({ :user_id => current_user.id }).at(0) %>
              <% if me %>
                <li class="nav-item">
                  <a class="nav-link" href="/brands/<%= me.id %>">
                    My Brand Profile
                  </a>
                </li>
              <% end %>
            <% end %>

            <li class="nav-item">
              <a class="nav-link" href="<%= destroy_user_session_path %>">
                Sign out
              </a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_session_path %>">Log in</a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="<%= new_user_registration_path(user_type: "athlete") %>"
              >
                Sign up Athlete
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="<%= new_user_registration_path(user_type: "brand") %>"
              >
                Sign up Brand
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show mt-5 mx-auto" style="max-width:600px;">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show mt-5 mx-auto" style="max-width:600px;">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    <% end %>

    <main class="container mt-4 pt-5">
      <%= yield %>
    </main>

    <!-- Bootstrap JS bundle -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-sENjdO4Dr2bkBIFxQpeoCKc0eMcQF14QuOE1L+/+xTIBhYxGxmY10XKApTI4M2xl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>